/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.bls;

public class Bls implements BlsConstants {
  public static void init(int curveType) {
    BlsJNI.init(curveType);
  }

  public static void setGeneratorOfPublicKey(PublicKey pub) {
    BlsJNI.setGeneratorOfPublicKey(PublicKey.getCPtr(pub), pub);
  }

  public static SecretKey share(SecretKeyVec secVec, SecretKey id) {
    return new SecretKey(BlsJNI.share__SWIG_0(SecretKeyVec.getCPtr(secVec), secVec, SecretKey.getCPtr(id), id), true);
  }

  public static PublicKey share(PublicKeyVec pubVec, SecretKey id) {
    return new PublicKey(BlsJNI.share__SWIG_1(PublicKeyVec.getCPtr(pubVec), pubVec, SecretKey.getCPtr(id), id), true);
  }

  public static SecretKey recover(SecretKeyVec secVec, SecretKeyVec idVec) {
    return new SecretKey(BlsJNI.recover__SWIG_0(SecretKeyVec.getCPtr(secVec), secVec, SecretKeyVec.getCPtr(idVec), idVec), true);
  }

  public static PublicKey recover(PublicKeyVec secVec, SecretKeyVec idVec) {
    return new PublicKey(BlsJNI.recover__SWIG_1(PublicKeyVec.getCPtr(secVec), secVec, SecretKeyVec.getCPtr(idVec), idVec), true);
  }

  public static Signature recover(SignatureVec sigVec, SecretKeyVec idVec) {
    return new Signature(BlsJNI.recover__SWIG_2(SignatureVec.getCPtr(sigVec), sigVec, SecretKeyVec.getCPtr(idVec), idVec), true);
  }

  public static void verifySignatureOrder(boolean doVerify) {
    BlsJNI.verifySignatureOrder(doVerify);
  }

  public static void verifyPublicKeyOrder(boolean doVerify) {
    BlsJNI.verifyPublicKeyOrder(doVerify);
  }

}
